// Lista consolidada de unidades cadastradas no projeto (plantas + insumos).
// Mantém o mesmo "case" usado nos cadastros para preservar consistência visual.
export const UNIDADES_COTACAO: string[] = [
  "Unid",
  "un",
  "Muda",
  "Pote",
  "Cuia",
  "Cuia 21",
  "1/2 Cuia",
  "Bdj",
  "Bag",
  "Cx",
  "Cx com 15",
  "Saco",
  "Pacote",
  "Touceira",
  "Torrão",
  "Raiz Nua",
  "Vaso",
  "Peça",
  "Par",
  "Rolo",
  "Galão",
  "Caixa",
  "kg",
  "Ton",
  "litro",
  "m",
  "m²",
  "m³",
];
