// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/_supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
function getEnv(name) {
  try {
    const g = globalThis;
    if (g?.process?.env?.[name]) return g.process.env[name];
    if (g?.Deno?.env?.get) return g.Deno.env.get(name);
  } catch {
  }
  return void 0;
}
function supabaseForUser(ctx) {
  const url = getEnv("SUPABASE_URL") || "https://placeholder.supabase.co";
  const anon = getEnv("SUPABASE_PUBLISHABLE_KEY") || getEnv("SUPABASE_ANON_KEY") || "placeholder";
  const token = ctx.getToken();
  return createClient(url, anon, {
    global: {
      headers: token ? { Authorization: `Bearer ${token}` } : {}
    },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function requireAuth(ctx) {
  if (!ctx.isAuthenticated()) {
    return {
      content: [{ type: "text", text: "N\xE3o autenticado." }],
      isError: true
    };
  }
  return null;
}

// src/lib/mcp/tools/whoami.ts
var whoami_default = defineTool({
  name: "whoami",
  title: "Quem sou eu",
  description: "Retorna informa\xE7\xF5es do usu\xE1rio autenticado (id, email, nome, pap\xE9is).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [profile, roles] = await Promise.all([
      supabase.from("profiles").select("id, nome, email, telefone, ativo").eq("id", userId).maybeSingle(),
      supabase.from("user_roles").select("role").eq("user_id", userId)
    ]);
    const data = {
      user_id: userId,
      email: ctx.getUserEmail(),
      profile: profile.data,
      roles: (roles.data ?? []).map((r) => r.role)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/list-clientes.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
var list_clientes_default = defineTool2({
  name: "list_clientes",
  title: "Listar clientes",
  description: "Lista clientes vis\xEDveis ao usu\xE1rio autenticado, com busca opcional por nome, cidade ou CPF/CNPJ. Respeita as permiss\xF5es (RLS) do usu\xE1rio.",
  inputSchema: {
    busca: z.string().trim().optional().describe("Termo de busca (nome, cidade, CPF/CNPJ)."),
    status: z.string().optional().describe("Filtrar por status (ex.: 'ativo', 'inativo')."),
    limite: z.number().int().min(1).max(100).optional().describe("M\xE1ximo de resultados (padr\xE3o 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ busca, status, limite }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("clientes").select("id, nome, email, telefone, cidade, estado, status, cpf_cnpj, created_at").order("nome", { ascending: true }).limit(limite ?? 25);
    if (status) q = q.eq("status", status);
    if (busca) {
      const like = `%${busca}%`;
      q = q.or(`nome.ilike.${like},cidade.ilike.${like},cpf_cnpj.ilike.${like}`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { count: data?.length ?? 0, clientes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-cliente.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_cliente_default = defineTool3({
  name: "get_cliente",
  title: "Detalhes do cliente",
  description: "Retorna dados detalhados de um cliente pelo id, incluindo projetos vinculados.",
  inputSchema: {
    cliente_id: z2.string().uuid().describe("UUID do cliente.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ cliente_id }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const supabase = supabaseForUser(ctx);
    const [cliente, projetos] = await Promise.all([
      supabase.from("clientes").select("*").eq("id", cliente_id).maybeSingle(),
      supabase.from("projetos").select("id, titulo, tipo, status, data_inicio, data_previsao, valor_total").eq("cliente_id", cliente_id).order("created_at", { ascending: false })
    ]);
    if (cliente.error) return { content: [{ type: "text", text: cliente.error.message }], isError: true };
    if (!cliente.data) return { content: [{ type: "text", text: "Cliente n\xE3o encontrado." }], isError: true };
    const payload = { cliente: cliente.data, projetos: projetos.data ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-projetos.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_projetos_default = defineTool4({
  name: "list_projetos",
  title: "Listar projetos",
  description: "Lista projetos vis\xEDveis ao usu\xE1rio (respeita aloca\xE7\xE3o e RLS). Filtre por status, tipo ou cliente.",
  inputSchema: {
    status: z3.string().optional().describe("Ex.: 'em_andamento', 'concluido'."),
    tipo: z3.string().optional().describe("Ex.: 'implantacao', 'manutencao'."),
    cliente_id: z3.string().uuid().optional(),
    busca: z3.string().trim().optional().describe("Busca por t\xEDtulo."),
    limite: z3.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, tipo, cliente_id, busca, limite }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("projetos").select("id, titulo, tipo, status, cliente_id, data_inicio, data_previsao, data_conclusao, valor_total, valor_mensal, responsavel_id").order("created_at", { ascending: false }).limit(limite ?? 25);
    if (status) q = q.eq("status", status);
    if (tipo) q = q.eq("tipo", tipo);
    if (cliente_id) q = q.eq("cliente_id", cliente_id);
    if (busca) q = q.ilike("titulo", `%${busca}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { count: data?.length ?? 0, projetos: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-crm-cards.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
var list_crm_cards_default = defineTool5({
  name: "list_crm_cards",
  title: "Listar cards do CRM",
  description: "Lista cards do funil de CRM (leads, propostas, aprovados, em execu\xE7\xE3o, etc). Respeita RLS do usu\xE1rio.",
  inputSchema: {
    status: z4.string().optional().describe("Ex.: 'Lead', 'Proposta Enviada', 'Aprovado', 'Em Execucao', 'Concluido', 'Pos-venda', 'Nao Aprovado'."),
    cliente_id: z4.string().uuid().optional(),
    busca: z4.string().trim().optional().describe("Busca por t\xEDtulo ou nome do contato."),
    limite: z4.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, cliente_id, busca, limite }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("crm_cards").select("id, titulo, tipo, status, cliente_id, projeto_id, contato_nome, contato_email, contato_whatsapp, prazo, responsavel_id, created_at").order("updated_at", { ascending: false }).limit(limite ?? 25);
    if (status) q = q.eq("status", status);
    if (cliente_id) q = q.eq("cliente_id", cliente_id);
    if (busca) {
      const like = `%${busca}%`;
      q = q.or(`titulo.ilike.${like},contato_nome.ilike.${like}`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { count: data?.length ?? 0, cards: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-crm-card.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^4.4.3";
var create_crm_card_default = defineTool6({
  name: "create_crm_card",
  title: "Criar card no CRM",
  description: "Cria um novo card (lead) no funil de CRM. O card \xE9 criado com o usu\xE1rio autenticado como respons\xE1vel quando n\xE3o indicado.",
  inputSchema: {
    titulo: z5.string().trim().min(1).describe("T\xEDtulo do card (obrigat\xF3rio)."),
    tipo: z5.string().trim().min(1).describe("Tipo do card (ex.: 'Implanta\xE7\xE3o', 'Manuten\xE7\xE3o')."),
    status: z5.string().trim().optional().describe("Status inicial (padr\xE3o 'Lead')."),
    cliente_id: z5.string().uuid().nullable().optional(),
    projeto_id: z5.string().uuid().nullable().optional(),
    contato_nome: z5.string().trim().nullable().optional(),
    contato_email: z5.string().trim().nullable().optional(),
    contato_whatsapp: z5.string().trim().nullable().optional(),
    observacoes: z5.string().trim().nullable().optional(),
    prazo: z5.string().trim().nullable().optional().describe("Data em ISO (YYYY-MM-DD).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const supabase = supabaseForUser(ctx);
    const { data: colaborador } = await supabase.from("colaboradores").select("id").eq("user_id", ctx.getUserId()).maybeSingle();
    const row = {
      titulo: input.titulo,
      tipo: input.tipo,
      status: input.status ?? "Lead",
      cliente_id: input.cliente_id ?? null,
      projeto_id: input.projeto_id ?? null,
      contato_nome: input.contato_nome ?? null,
      contato_email: input.contato_email ?? null,
      contato_whatsapp: input.contato_whatsapp ?? null,
      observacoes: input.observacoes ?? null,
      prazo: input.prazo ?? null,
      responsavel_id: colaborador?.id ?? null
    };
    const { data, error } = await supabase.from("crm_cards").insert(row).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Card criado (id ${data?.id}).` }],
      structuredContent: { card: data }
    };
  }
});

// src/lib/mcp/tools/describe-schema.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z6 } from "npm:zod@^4.4.3";
var describe_schema_default = defineTool7({
  name: "describe_schema",
  title: "Descrever schema",
  description: "Introspec\xE7\xE3o s\xF3-leitura do schema public. Sem par\xE2metro, lista todas as tabelas com contagem de colunas e status de RLS. Com 'tabela', devolve colunas, chave prim\xE1ria, chaves estrangeiras e status de RLS. Nunca l\xEA dados.",
  inputSchema: {
    tabela: z6.string().trim().optional().describe("Nome da tabela do schema public. Omita para listar todas.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tabela }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const supabase = supabaseForUser(ctx);
    if (!tabela) {
      const { data: data2, error: error2 } = await supabase.rpc("mcp_list_public_tables");
      if (error2) return { content: [{ type: "text", text: error2.message }], isError: true };
      return {
        content: [{ type: "text", text: JSON.stringify(data2, null, 2) }],
        structuredContent: { tabelas: data2 ?? [] }
      };
    }
    const { data, error } = await supabase.rpc("mcp_describe_table", { p_tabela: tabela });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (data && typeof data === "object" && "erro" in data) {
      return {
        content: [{ type: "text", text: String(data.erro) }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/read-table.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z7 } from "npm:zod@^4.4.3";
var read_table_default = defineTool8({
  name: "read_table",
  title: "Ler tabela",
  description: "Leitura gen\xE9rica de qualquer tabela do schema public, respeitando as permiss\xF5es (RLS) do usu\xE1rio autenticado. S\xF3 retorna o que o usu\xE1rio tem permiss\xE3o para ver.",
  inputSchema: {
    tabela: z7.string().trim().min(1).describe("Nome da tabela do schema public."),
    colunas: z7.string().trim().optional().describe("Lista de colunas separadas por v\xEDrgula (padr\xE3o '*')."),
    filtros: z7.record(z7.string(), z7.union([z7.string(), z7.number(), z7.boolean(), z7.null()])).optional().describe("Objeto campo\u2192valor para igualdade estrita."),
    ordenar_por: z7.string().trim().optional().describe("Coluna para ordenar. Prefixe com '-' para descendente (ex.: '-created_at')."),
    limite: z7.number().int().min(1).max(100).optional().describe("Padr\xE3o 25, m\xE1ximo 100."),
    offset: z7.number().int().min(0).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tabela, colunas, filtros, ordenar_por, limite, offset }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const supabase = supabaseForUser(ctx);
    const { data: tabelas, error: eList } = await supabase.rpc("mcp_list_public_tables");
    if (eList) return { content: [{ type: "text", text: eList.message }], isError: true };
    const nomes = new Set(
      tabelas?.map((t) => t.tabela) ?? []
    );
    if (!nomes.has(tabela)) {
      return {
        content: [{ type: "text", text: `Tabela "${tabela}" n\xE3o existe no schema public.` }],
        isError: true
      };
    }
    const lim = Math.min(limite ?? 25, 100);
    const off = offset ?? 0;
    let q = supabase.from(tabela).select(colunas ?? "*").range(off, off + lim - 1);
    if (filtros && typeof filtros === "object") {
      for (const [k, v] of Object.entries(filtros)) {
        q = v === null ? q.is(k, null) : q.eq(k, v);
      }
    }
    if (ordenar_por) {
      const desc = ordenar_por.startsWith("-");
      const col = desc ? ordenar_por.slice(1) : ordenar_por;
      q = q.order(col, { ascending: !desc });
    }
    const { data, error } = await q;
    if (error) {
      const msg = /permission denied|row-level security/i.test(error.message) ? `Acesso negado \xE0 tabela "${tabela}" para o usu\xE1rio atual (RLS).` : error.message;
      return { content: [{ type: "text", text: msg }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { tabela, count: data?.length ?? 0, linhas: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-storage.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z8 } from "npm:zod@^4.4.3";
var list_storage_default = defineTool9({
  name: "list_storage",
  title: "Listar Storage",
  description: "Lista buckets ou arquivos do Storage. Sem par\xE2metro, devolve buckets (nome, p\xFAblico/privado). Com 'bucket' (e 'prefixo' opcional), lista arquivos (nome, tamanho, criado em), m\xE1ximo 100. N\xE3o devolve conte\xFAdo nem URLs assinadas.",
  inputSchema: {
    bucket: z8.string().trim().optional().describe("Nome do bucket."),
    prefixo: z8.string().trim().optional().describe("Prefixo (pasta) dentro do bucket.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ bucket, prefixo }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const supabase = supabaseForUser(ctx);
    if (!bucket) {
      const { data: data2, error: error2 } = await supabase.storage.listBuckets();
      if (error2) return { content: [{ type: "text", text: error2.message }], isError: true };
      const buckets = (data2 ?? []).map((b) => ({
        nome: b.name,
        publico: b.public,
        criado_em: b.created_at
      }));
      return {
        content: [{ type: "text", text: JSON.stringify(buckets, null, 2) }],
        structuredContent: { buckets }
      };
    }
    const { data, error } = await supabase.storage.from(bucket).list(prefixo ?? "", { limit: 100, sortBy: { column: "name", order: "asc" } });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const arquivos = (data ?? []).map((f) => ({
      nome: f.name,
      tamanho: f.metadata?.size ?? null,
      mimetype: f.metadata?.mimetype ?? null,
      criado_em: f.created_at,
      atualizado_em: f.updated_at
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(arquivos, null, 2) }],
      structuredContent: { bucket, prefixo: prefixo ?? "", count: arquivos.length, arquivos }
    };
  }
});

// src/lib/mcp/tools/criar-registros.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z9 } from "npm:zod@^4.4.3";

// src/lib/mcp/tools/_validacao.ts
function normalizarValor(v) {
  return String(v ?? "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").trim().toLowerCase().replace(/[\s-]+/g, "_");
}
function normalizarTexto(v) {
  return String(v ?? "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
}
var TIPOS_REGISTRO = [
  "manutencao",
  "implantacao",
  "entrega",
  "visita_tecnica",
  "reuniao",
  "outro",
  "visita",
  "tarefa",
  "acompanhamento",
  "intercorrencia",
  "solicitacao",
  "observacao",
  "irrigacao"
];
var STATUS_REGISTRO = [
  // rotina da visita
  "programado",
  "realizado",
  "reportado",
  "validado",
  // análise e orçamento
  "solicitado",
  "a_quantificar",
  "quantificando",
  "a_orcar",
  "orcando",
  "aguardando_aprovacao",
  // preparação
  "planejar_execucao",
  "aguardando_material",
  "retirar_material",
  // execução
  "executando",
  "a_fazer",
  "em_andamento",
  "travado",
  // acompanhamento
  "pos_execucao",
  "em_observacao",
  "em_cuidado",
  "reaberto",
  // encerramento
  "concluido",
  "nao_aprovado",
  "cancelado"
];
var TIPOS_ESCALA = ["projeto", "mao_de_obra_extra"];
var STATUS_ESCALA = [
  "planejada",
  "confirmada",
  "realizada",
  "cancelada"
];
var TIPOS_PROJETO = [
  "implantacao",
  "obra",
  "manutencao",
  "fornecimento",
  "projeto",
  "mao_de_obra"
];
var STATUS_PROJETO = [
  "prospeccao",
  "qualificacao",
  "projeto",
  "orcamento",
  "proposta",
  "aprovado",
  "em_execucao",
  "concluido",
  "perdido",
  "cancelado"
];
var PRIORIDADES = ["alta", "normal", "baixa"];
var SOLICITANTES = ["equipe", "cliente", "caseiro", "contrato"];
var AREAS_FUNCIONAIS = [
  "campo",
  "projetos",
  "administrativo",
  "direcao"
];
var TIPOS_POR_TABELA = {
  registros: TIPOS_REGISTRO,
  escala_alocacoes: TIPOS_ESCALA,
  diarias: TIPOS_REGISTRO,
  projetos: TIPOS_PROJETO
};
var STATUS_POR_TABELA = {
  registros: STATUS_REGISTRO,
  escala_alocacoes: STATUS_ESCALA,
  diarias: STATUS_REGISTRO,
  projetos: STATUS_PROJETO
};
var SUBSTATUS_PROJETO = STATUS_REGISTRO;
var STATUS_POR_TIPO = {
  visita: ["programado", "realizado", "reportado", "validado", "cancelado"],
  tarefa: [
    "solicitado",
    "a_quantificar",
    "quantificando",
    "a_orcar",
    "orcando",
    "aguardando_aprovacao",
    "planejar_execucao",
    "aguardando_material",
    "retirar_material",
    "executando",
    "a_fazer",
    "em_andamento",
    "travado",
    "concluido",
    "nao_aprovado",
    "cancelado"
  ],
  acompanhamento: [
    "em_observacao",
    "em_cuidado",
    "pos_execucao",
    "reaberto",
    "concluido"
  ],
  irrigacao: [
    "em_observacao",
    "em_cuidado",
    "a_fazer",
    "em_andamento",
    "concluido",
    "cancelado"
  ]
};
function validarValoresRegistro(campos, tabela = "registros") {
  const out = { ...campos };
  const checar = (campo, permitidos) => {
    if (!permitidos) return null;
    if (campos[campo] === void 0 || campos[campo] === null) return null;
    const v = normalizarValor(campos[campo]);
    if (!permitidos.includes(v)) {
      return `${campo} '${campos[campo]}' n\xE3o vale para ${tabela}. Use: ${permitidos.join(", ")}.`;
    }
    out[campo] = v;
    return null;
  };
  const ehRegistros = tabela === "registros";
  const ehProjetos = tabela === "projetos";
  const erros = [
    checar("tipo", TIPOS_POR_TABELA[tabela]),
    checar("status", STATUS_POR_TABELA[tabela]),
    ehProjetos ? checar("substatus", SUBSTATUS_PROJETO) : null,
    ehRegistros ? checar("prioridade", PRIORIDADES) : null,
    ehRegistros ? checar("solicitante", SOLICITANTES) : null,
    ehRegistros ? checar("area_funcional", AREAS_FUNCIONAIS) : null
  ].filter(Boolean);
  if (erros.length) return { erro: erros.join(" ") };
  if (ehRegistros) {
    const tipo = out.tipo;
    const status = out.status;
    if (tipo && status) {
      const permitidos = STATUS_POR_TIPO[tipo];
      if (permitidos && !permitidos.includes(status)) {
        return {
          erro: `status '${status}' n\xE3o vale para tipo=${tipo}. Para tipo=${tipo} use: ${permitidos.join(", ")}.`
        };
      }
    }
  }
  return { valores: out };
}
function validarStatusRegistroComTipo(statusBruto, tipoAtual, tabela = "registros") {
  const status = normalizarValor(statusBruto);
  const permitidosTabela = STATUS_POR_TABELA[tabela] ?? STATUS_REGISTRO;
  if (!permitidosTabela.includes(status)) {
    return {
      erro: `status '${statusBruto}' n\xE3o vale para ${tabela}. Use: ${permitidosTabela.join(", ")}.`
    };
  }
  if (tabela === "registros") {
    const tipo = normalizarValor(tipoAtual);
    const permitidos = STATUS_POR_TIPO[tipo];
    if (permitidos && !permitidos.includes(status)) {
      return {
        erro: `status '${status}' n\xE3o vale para tipo=${tipo}. Para tipo=${tipo} use: ${permitidos.join(", ")}.`
      };
    }
  }
  return { status };
}
var CAMPOS_TEXTO_ACUMULAVEL = /* @__PURE__ */ new Set([
  "observacoes",
  "observacoes_internas",
  "descricao",
  "assessores",
  "funcionarios_casa",
  "comentarios_jardim",
  "ocorrencias"
]);
function acrescentarTexto(atual, novo) {
  const a = typeof atual === "string" ? atual.trim() : "";
  const b = String(novo ?? "").trim();
  if (!a) return b;
  if (!b) return a;
  return `${a} | ${b}`;
}
function filtrarCampos(linha, permitidos, obrigatorios, tabela) {
  const desconhecidos = Object.keys(linha).filter(
    (k) => !permitidos.includes(k)
  );
  if (desconhecidos.length) {
    return {
      erro: `Campo(s) n\xE3o aceito(s) em '${tabela}': ${desconhecidos.join(", ")}. Aceitos: ${permitidos.join(", ")}.`
    };
  }
  const faltando = obrigatorios.filter(
    (k) => linha[k] === void 0 || linha[k] === null || linha[k] === ""
  );
  if (faltando.length) {
    return {
      erro: `Faltam campos obrigat\xF3rios em '${tabela}': ${faltando.join(", ")}.`
    };
  }
  return { payload: { ...linha } };
}
var TEM_AUTORIA = /* @__PURE__ */ new Set([
  "projetos",
  "registros",
  "diarias",
  "clientes",
  "colaboradores",
  "fornecedor_atendentes",
  "fornecedores",
  "insumo_unidades",
  "insumos",
  "maquinas",
  "plantas",
  "locais_cliente"
]);
async function nomeDoUsuario(supabase, userId, email) {
  try {
    const { data: col } = await supabase.from("colaboradores").select("nome").eq("user_id", userId).maybeSingle();
    const nomeCol = col?.nome;
    if (nomeCol) return nomeCol;
  } catch {
  }
  try {
    const { data: p } = await supabase.from("profiles").select("nome,email").eq("id", userId).maybeSingle();
    const prof = p;
    if (prof?.nome) return prof.nome;
    if (prof?.email) return prof.email;
  } catch {
  }
  return email ?? userId;
}
async function registrarMudancaStatus(supabase, params) {
  const { error } = await supabase.from("audit_status_changes").insert({
    entity_table: params.entityTable,
    entity_id: params.entityId,
    status_anterior: params.statusAnterior === null || params.statusAnterior === void 0 ? null : String(params.statusAnterior),
    status_novo: params.statusNovo === null || params.statusNovo === void 0 ? null : String(params.statusNovo),
    changed_by: params.changedBy,
    changed_by_nome: params.changedByNome,
    metadata: {
      motivo: params.motivo ?? "",
      quem_executou: params.quemExecutou ?? params.changedByNome,
      observacao: params.observacao ?? ""
    }
  });
  if (error) {
    return {
      ok: false,
      aviso: `A altera\xE7\xE3o foi gravada, mas o hist\xF3rico de status n\xE3o p\xF4de ser registrado (${error.message}). Avise a administra\xE7\xE3o para liberar a escrita em audit_status_changes.`
    };
  }
  return { ok: true };
}

// src/lib/mcp/tools/criar-registros.ts
var TABELAS = [
  "clientes",
  "locais_cliente",
  "colaboradores",
  "maquinas",
  "insumos",
  "insumo_unidades",
  "plantas",
  "fornecedores",
  "fornecedor_atendentes",
  "estoque_movimentacoes",
  // operação de campo
  "projetos",
  "registros",
  "diarias",
  "escala_alocacoes",
  "registro_insumos",
  "registro_maquinas"
];
var TEM_CREATED_BY = /* @__PURE__ */ new Set([
  "clientes",
  "colaboradores",
  "fornecedor_atendentes",
  "fornecedores",
  "insumo_unidades",
  "insumos",
  "maquinas",
  "plantas"
]);
var DEDUP_CAT = {
  plantas: "planta",
  insumos: "insumo"
};
var CAMPOS_OPERACAO = {
  projetos: {
    obrigatorios: ["cliente_id", "titulo", "tipo", "status"],
    permitidos: [
      "cliente_id",
      "titulo",
      "tipo",
      "status",
      "local_id",
      "descricao",
      "observacoes",
      "valor_total",
      "valor_mensal",
      "dia_vencimento",
      "data_inicio",
      "data_previsao",
      "responsavel_id",
      "lider_responsavel_id",
      "usa_mao_de_obra_campo",
      "origem",
      "escala_periodicidade",
      "escala_dias_semana",
      "escala_duracao_dias",
      "escala_equipe_qtd"
    ]
  },
  registros: {
    obrigatorios: ["cliente_id", "data_servico", "tipo", "descricao", "status"],
    permitidos: [
      "cliente_id",
      "data_servico",
      "tipo",
      "descricao",
      "status",
      "local_id",
      "projeto_id",
      "trecho_id",
      "diaria_id",
      "prioridade",
      "solicitante",
      "area_funcional",
      "observacoes_internas",
      "equipe_presente_ids",
      "executores_ids",
      "data_alerta",
      "tags",
      "midia"
    ]
  },
  diarias: {
    obrigatorios: ["cliente_id", "data_visita"],
    permitidos: [
      "cliente_id",
      "data_visita",
      "trecho_id",
      "periodo",
      "equipe_presente_ids",
      "comentarios_jardim",
      "observacoes_internas",
      "status",
      "data_alerta"
    ]
  },
  escala_alocacoes: {
    obrigatorios: ["data", "colaborador_id", "tipo"],
    permitidos: [
      "data",
      "colaborador_id",
      "tipo",
      "projeto_id",
      "local_id",
      "lider_id",
      "status",
      "diaria_id",
      "observacoes"
    ]
  },
  registro_insumos: {
    obrigatorios: ["registro_id", "insumo_id", "quantidade"],
    permitidos: ["registro_id", "insumo_id", "quantidade", "observacao"]
  },
  registro_maquinas: {
    obrigatorios: ["registro_id", "maquina_id", "horas_utilizadas"],
    permitidos: ["registro_id", "maquina_id", "horas_utilizadas", "observacao"]
  }
};
var criar_registros_default = defineTool10({
  name: "criar_registros",
  title: "Criar registros em lote",
  description: "Cria linhas em lote em tabelas de cadastro e da opera\xE7\xE3o de campo (whitelist). Cadastro (plantas, insumos, fornecedores) roda deduplica\xE7\xE3o por nome. Opera\xE7\xE3o (projetos, registros, diarias, escala_alocacoes, registro_insumos, registro_maquinas) roda valida\xE7\xE3o de campos/valores e prote\xE7\xE3o contra grava\xE7\xE3o repetida por chave natural: diarias = cliente_id + data_visita; registros = cliente_id + data_servico + tipo + descri\xE7\xE3o parecida; escala_alocacoes = data + colaborador_id + local_id. Use forcar=true para criar mesmo assim. M\xE1x 50 linhas por chamada. Escreve com o token do usu\xE1rio (RLS ativa).",
  inputSchema: {
    tabela: z9.enum(TABELAS).describe("Tabela alvo. Aceita apenas: " + TABELAS.join(", ")),
    linhas: z9.array(z9.record(z9.string(), z9.unknown())).min(1).max(50).describe("Array de objetos (m\xE1x 50)."),
    forcar: z9.boolean().optional().describe(
      "Se true, cria mesmo quando houver poss\xEDvel duplicado ou visita repetida."
    )
  },
  annotations: {
    readOnlyHint: false,
    destructiveHint: false,
    idempotentHint: false,
    openWorldHint: false
  },
  handler: async ({ tabela, linhas, forcar }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const tbl = tabela;
    const regrasOperacao = CAMPOS_OPERACAO[tbl];
    const ehOperacao = Boolean(regrasOperacao);
    const dedupTipo = ehOperacao ? void 0 : DEDUP_CAT[tbl];
    const isFornecedor = !ehOperacao && tbl === "fornecedores";
    const resultados = [];
    for (let i = 0; i < linhas.length; i++) {
      const raw = linhas[i];
      try {
        const nome = typeof raw.nome === "string" ? raw.nome.trim() : "";
        if (!forcar && dedupTipo && nome) {
          const { data: matches, error: eMatch } = await supabase.rpc(
            "match_catalogo",
            { p_tipo: dedupTipo, p_query: nome, p_limit: 1 }
          );
          if (eMatch) {
            resultados.push({
              indice: i,
              status: "erro",
              motivo: `dedup falhou: ${eMatch.message}`
            });
            continue;
          }
          const top = matches?.[0];
          if (top && top.score >= 0.9) {
            resultados.push({
              indice: i,
              status: "pulada",
              motivo: "poss\xEDvel duplicado (score >= 0.90)",
              duplicado: {
                id: top.item_id,
                nome: top.nome,
                score: top.score,
                fonte: top.fonte
              }
            });
            continue;
          }
        }
        if (!forcar && isFornecedor && nome) {
          const { data: norm } = await supabase.rpc(
            "norm_catalogo",
            { t: nome }
          );
          const chave = norm ?? nome.toLowerCase().trim();
          const { data: cand } = await supabase.from("fornecedores").select("id, nome").ilike("nome", `%${nome}%`).limit(5);
          const hit = (cand ?? []).find(
            (c) => (c.nome ?? "").trim().toLowerCase() === nome.toLowerCase() || (c.nome ?? "").trim().toLowerCase() === String(chave).toLowerCase()
          );
          if (hit) {
            resultados.push({
              indice: i,
              status: "pulada",
              motivo: "fornecedor com nome id\xEAntico j\xE1 existe",
              duplicado: { id: hit.id, nome: hit.nome, score: 1, fonte: "exato" }
            });
            continue;
          }
        }
        let payload = { ...raw };
        if (regrasOperacao) {
          const filtrado = filtrarCampos(
            raw,
            regrasOperacao.permitidos,
            regrasOperacao.obrigatorios,
            tbl
          );
          if ("erro" in filtrado) {
            resultados.push({ indice: i, status: "erro", motivo: filtrado.erro });
            continue;
          }
          payload = filtrado.payload;
          if (tbl === "registros" || tbl === "escala_alocacoes" || tbl === "diarias" || tbl === "projetos") {
            const validado = validarValoresRegistro(payload, tbl);
            if ("erro" in validado) {
              resultados.push({ indice: i, status: "erro", motivo: validado.erro });
              continue;
            }
            payload = validado.valores;
          }
          if (tbl === "escala_alocacoes" && !payload.projeto_id && !payload.local_id) {
            resultados.push({
              indice: i,
              status: "erro",
              motivo: "escala_alocacoes precisa de projeto_id ou local_id. Informe pelo menos um dos dois para dizer onde a pessoa vai trabalhar."
            });
            continue;
          }
        }
        if (!forcar && tbl === "diarias") {
          const { data: existente } = await supabase.from("diarias").select("id, comentarios_jardim, observacoes_internas, status, periodo").eq("cliente_id", payload.cliente_id).eq("data_visita", payload.data_visita).limit(1).maybeSingle();
          if (existente) {
            resultados.push({
              indice: i,
              status: "pulada",
              motivo: "j\xE1 existe visita para esta casa nesta data. Para completar, use atualizar_registro (modo acrescentar). Para criar assim mesmo, chame de novo com forcar=true.",
              duplicado: {
                id: existente.id,
                fonte: "cliente_id + data_visita",
                mudaria: diffPreview(existente, payload)
              }
            });
            continue;
          }
        }
        if (!forcar && tbl === "registros") {
          const { data: cands } = await supabase.from("registros").select("id, descricao").eq("cliente_id", payload.cliente_id).eq("data_servico", payload.data_servico).eq("tipo", payload.tipo).limit(20);
          const alvo = normalizarTexto(payload.descricao);
          const hit = (cands ?? []).find((c) => {
            const d = normalizarTexto(c.descricao);
            if (!d || !alvo) return false;
            return d === alvo || alvo.length > 20 && (d.includes(alvo) || alvo.includes(d));
          });
          if (hit) {
            resultados.push({
              indice: i,
              status: "pulada",
              motivo: "j\xE1 existe registro muito parecido para este cliente, data e tipo. Para criar assim mesmo, chame de novo com forcar=true.",
              duplicado: {
                id: hit.id,
                fonte: "cliente_id + data_servico + tipo + descri\xE7\xE3o parecida",
                mudaria: diffPreview({ descricao: hit.descricao }, payload)
              }
            });
            continue;
          }
        }
        if (!forcar && tbl === "escala_alocacoes") {
          let q = supabase.from("escala_alocacoes").select("id, status, lider_id, observacoes").eq("data", payload.data).eq("colaborador_id", payload.colaborador_id);
          q = payload.local_id ? q.eq("local_id", payload.local_id) : q.is("local_id", null);
          const { data: existente } = await q.limit(1).maybeSingle();
          if (existente) {
            resultados.push({
              indice: i,
              status: "pulada",
              motivo: "esta pessoa j\xE1 est\xE1 alocada nesta data e neste local. Para criar assim mesmo, chame de novo com forcar=true.",
              duplicado: {
                id: existente.id,
                fonte: "data + colaborador_id + local_id",
                mudaria: diffPreview(existente, payload)
              }
            });
            continue;
          }
        }
        if ((TEM_CREATED_BY.has(tbl) || TEM_AUTORIA.has(tbl)) && payload.created_by === void 0) {
          payload.created_by = userId;
          payload.updated_by = userId;
        }
        const { data, error } = await supabase.from(tbl).insert(payload).select("id").maybeSingle();
        if (error) {
          const msg = /permission denied|row-level security/i.test(error.message) ? `acesso negado por RLS: ${error.message}` : error.message;
          resultados.push({ indice: i, status: "erro", motivo: msg });
          continue;
        }
        resultados.push({
          indice: i,
          status: "criada",
          id: data?.id
        });
      } catch (e) {
        resultados.push({
          indice: i,
          status: "erro",
          motivo: e instanceof Error ? e.message : String(e)
        });
      }
    }
    const sumario = {
      criadas: resultados.filter((r) => r.status === "criada").length,
      puladas: resultados.filter((r) => r.status === "pulada").length,
      erros: resultados.filter((r) => r.status === "erro").length
    };
    return {
      content: [
        {
          type: "text",
          text: `Tabela ${tbl}: ${sumario.criadas} criadas, ${sumario.puladas} puladas (j\xE1 existiam), ${sumario.erros} com erro.`
        }
      ],
      structuredContent: { tabela: tbl, sumario, resultados }
    };
  }
});
function diffPreview(existente, nova) {
  const diff = {};
  for (const [k, v] of Object.entries(nova)) {
    if (k === "cliente_id" || k === "created_by" || k === "updated_by") continue;
    if (!(k in existente)) continue;
    if (JSON.stringify(existente[k]) !== JSON.stringify(v)) {
      diff[k] = { atual: existente[k], novo: v };
    }
  }
  return diff;
}

// src/lib/mcp/tools/atualizar-registro.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z10 } from "npm:zod@^4.4.3";
var TABELAS2 = [
  "clientes",
  "locais_cliente",
  "colaboradores",
  "maquinas",
  "insumos",
  "insumo_unidades",
  "plantas",
  "fornecedores",
  "fornecedor_atendentes",
  "estoque_movimentacoes",
  "projetos",
  "registros",
  "diarias",
  "escala_alocacoes",
  "registro_insumos",
  "registro_maquinas"
];
var CAMPOS_UPDATE = {
  projetos: [
    "tipo",
    "status",
    "titulo",
    "responsavel_id",
    "data_inicio",
    "data_fim",
    "data_previsao",
    "data_conclusao",
    "valor_mensal",
    "dia_vencimento",
    "local_id",
    "lider_responsavel_id",
    "escala_periodicidade",
    "escala_dias_semana",
    "escala_duracao_dias",
    "escala_equipe_qtd"
  ],
  registros: [
    "status",
    "descricao",
    "observacoes_internas",
    "prioridade",
    "data_alerta",
    "status_solicitacao",
    "tags",
    "midia",
    "trecho_id",
    "area_funcional",
    "equipe_presente_ids",
    "executores_ids",
    "solicitante"
  ],
  diarias: [
    "status",
    "comentarios_jardim",
    "observacoes_internas",
    "equipe_presente_ids",
    "periodo",
    "data_alerta",
    "trecho_id"
  ],
  escala_alocacoes: ["status", "lider_id", "observacoes", "diaria_id"],
  registro_insumos: ["quantidade", "observacao"],
  registro_maquinas: ["horas_utilizadas", "observacao"]
};
var CAMPOS_BLOQUEADOS = {
  registros: {
    cliente_id: "mover um registro de casa por engano \xE9 pior que apagar e refazer. Crie um novo registro na casa certa e cancele este.",
    local_id: "mover um registro de local por engano \xE9 pior que apagar e refazer. Crie um novo registro no local certo e cancele este.",
    projeto_id: "mover um registro de projeto por engano \xE9 pior que apagar e refazer. Crie um novo registro no projeto certo e cancele este."
  }
};
var atualizar_registro_default = defineTool11({
  name: "atualizar_registro",
  title: "Atualizar registro por id",
  description: "Atualiza UMA linha por id em tabelas de cadastro e da opera\xE7\xE3o de campo (whitelist), com campos restritos por tabela. Use modo='acrescentar' para somar texto ao que j\xE1 existe (separado por ' | ') em vez de sobrescrever. Toda mudan\xE7a de status \xE9 gravada em audit_status_changes com metadata padronizado (motivo, quem_executou, observacao). Escreve com o token do usu\xE1rio (RLS ativa). Retorna antes \u2192 depois.",
  inputSchema: {
    tabela: z10.enum(TABELAS2).describe("Tabela alvo. Aceita: " + TABELAS2.join(", ")),
    id: z10.string().uuid().describe("UUID da linha."),
    campos: z10.record(z10.string(), z10.unknown()).describe("Campos a atualizar (objeto). N\xE3o passe id."),
    modo: z10.enum(["substituir", "acrescentar"]).optional().describe(
      "substituir (padr\xE3o) troca o valor. acrescentar soma o texto novo ao existente, separado por ' | ', nos campos de texto livre."
    ),
    motivo: z10.string().optional().describe("Por que o status mudou (vai para o hist\xF3rico)."),
    quem_executou: z10.string().optional().describe("Quem de fato executou (vai para o hist\xF3rico)."),
    observacao: z10.string().optional().describe("Observa\xE7\xE3o livre sobre a mudan\xE7a (vai para o hist\xF3rico).")
  },
  annotations: {
    readOnlyHint: false,
    destructiveHint: false,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async ({ tabela, id, campos, modo, motivo, quem_executou, observacao }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const tbl = tabela;
    const acrescentar = modo === "acrescentar";
    const entries = Object.entries(campos).filter(
      ([k]) => k !== "id" && k !== "created_by" && k !== "updated_by"
    );
    if (entries.length === 0) {
      return {
        content: [{ type: "text", text: "Nenhum campo para atualizar." }],
        isError: true
      };
    }
    const bloqueados = CAMPOS_BLOQUEADOS[tbl];
    if (bloqueados) {
      const batidos = entries.filter(([k]) => bloqueados[k]);
      if (batidos.length) {
        return {
          content: [
            {
              type: "text",
              text: batidos.map(([k]) => `N\xE3o \xE9 permitido alterar '${k}' em ${tbl}: ${bloqueados[k]}`).join(" ")
            }
          ],
          isError: true
        };
      }
    }
    const permitidos = CAMPOS_UPDATE[tbl];
    if (permitidos) {
      const invalidos = entries.filter(([k]) => !permitidos.includes(k)).map(([k]) => k);
      if (invalidos.length) {
        return {
          content: [
            {
              type: "text",
              text: `Em '${tbl}' s\xF3 \xE9 permitido atualizar: ${permitidos.join(", ")}. Rejeitados: ${invalidos.join(", ")}.`
            }
          ],
          isError: true
        };
      }
    }
    const colunasSet = new Set(entries.map(([k]) => k));
    if (tbl === "registros") colunasSet.add("tipo");
    if (colunasSet.has("status") === false) {
    } else {
      colunasSet.add("status");
    }
    const colunas = Array.from(colunasSet).join(",");
    const { data: antes, error: eAntes } = await supabase.from(tbl).select(`id,${colunas}`).eq("id", id).maybeSingle();
    if (eAntes) {
      return { content: [{ type: "text", text: eAntes.message }], isError: true };
    }
    if (!antes) {
      return {
        content: [
          {
            type: "text",
            text: `Registro ${id} n\xE3o encontrado em ${tbl} (ou sem permiss\xE3o de leitura).`
          }
        ],
        isError: true
      };
    }
    const antesObj = antes;
    const patch = {};
    for (const [k, v] of entries) {
      let valor = v;
      if (k === "status" && STATUS_POR_TABELA[tbl]) {
        const r = validarStatusRegistroComTipo(v, antesObj.tipo, tbl);
        if ("erro" in r) {
          return { content: [{ type: "text", text: r.erro }], isError: true };
        }
        valor = r.status;
      } else if (tbl === "registros" && k === "prioridade") {
        const n = normalizarValor(v);
        if (!PRIORIDADES.includes(n)) {
          return {
            content: [
              {
                type: "text",
                text: `prioridade '${v}' n\xE3o existe. Use: ${PRIORIDADES.join(", ")}.`
              }
            ],
            isError: true
          };
        }
        valor = n;
      } else if (tbl === "registros" && k === "solicitante") {
        const n = normalizarValor(v);
        if (!SOLICITANTES.includes(n)) {
          return {
            content: [
              {
                type: "text",
                text: `solicitante '${v}' n\xE3o existe. Use: ${SOLICITANTES.join(", ")}.`
              }
            ],
            isError: true
          };
        }
        valor = n;
      } else if (tbl === "registros" && k === "area_funcional") {
        const n = normalizarValor(v);
        if (!AREAS_FUNCIONAIS.includes(n)) {
          return {
            content: [
              {
                type: "text",
                text: `area_funcional '${v}' n\xE3o existe. Use: ${AREAS_FUNCIONAIS.join(", ")}.`
              }
            ],
            isError: true
          };
        }
        valor = n;
      }
      if (acrescentar && CAMPOS_TEXTO_ACUMULAVEL.has(k) && typeof valor === "string") {
        valor = acrescentarTexto(antesObj[k], valor);
      }
      patch[k] = valor;
    }
    if (TEM_AUTORIA.has(tbl)) {
      patch.updated_by = userId;
    }
    const { data: depois, error } = await supabase.from(tbl).update(patch).eq("id", id).select(`id,${colunas}`).maybeSingle();
    if (error) {
      const msg = /permission denied|row-level security/i.test(error.message) ? `acesso negado por RLS: ${error.message}` : error.message;
      return { content: [{ type: "text", text: msg }], isError: true };
    }
    const depoisObj = depois ?? {};
    const diff = {};
    for (const [k] of entries) {
      const a = antesObj[k];
      const d = depoisObj[k];
      if (JSON.stringify(a) !== JSON.stringify(d)) {
        diff[k] = { antes: a, depois: d };
      }
    }
    const avisos = [];
    if (diff.status) {
      const nome = await nomeDoUsuario(supabase, userId, ctx.getUserEmail?.());
      const res = await registrarMudancaStatus(supabase, {
        entityTable: tbl,
        entityId: id,
        statusAnterior: diff.status.antes,
        statusNovo: diff.status.depois,
        changedBy: userId,
        changedByNome: nome,
        motivo,
        quemExecutou: quem_executou,
        observacao
      });
      if (res.ok === false) avisos.push(res.aviso);
    }
    return {
      content: [
        {
          type: "text",
          text: `Registro ${id} em ${tbl} atualizado (${Object.keys(diff).length} campo(s) alterado(s))` + (acrescentar ? ", modo acrescentar" : "") + "." + (avisos.length ? " " + avisos.join(" ") : "")
        }
      ],
      structuredContent: {
        tabela: tbl,
        id,
        modo: acrescentar ? "acrescentar" : "substituir",
        alteracoes: diff,
        avisos
      }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "lelteebbziredzfamkzb";
var mcp_default = defineMcp({
  name: "mfm-paisagismo-mcp",
  title: "MFM Paisagismo",
  version: "0.1.0",
  instructions: "Ferramentas do sistema MFM Paisagismo. Permite consultar clientes, projetos e cards do CRM, criar leads, e leitura gen\xE9rica de tabelas/schema/storage para auditoria e arquitetura. Toda opera\xE7\xE3o executa como o usu\xE1rio autenticado e respeita as permiss\xF5es (RLS).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_clientes_default,
    get_cliente_default,
    list_projetos_default,
    list_crm_cards_default,
    create_crm_card_default,
    describe_schema_default,
    read_table_default,
    list_storage_default,
    criar_registros_default,
    atualizar_registro_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
